"""create growth_stages

Revision ID: 5b10439fdc69
Revises: 6966518b98df
Create Date: 2026-09-20 19:29:15.391542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b10439fdc69'
down_revision: Union[str, Sequence[str], None] = '6966518b98df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('growth_stages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('ec_min', sa.Float(), nullable=False),
    sa.Column('ec_target', sa.Float(), nullable=False),
    sa.Column('ec_max', sa.Float(), nullable=False),
    sa.Column('ph_min', sa.Float(), nullable=False),
    sa.Column('ph_target', sa.Float(), nullable=False),
    sa.Column('ph_max', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('growth_stages')
    # ### end Alembic commands ###
