"""create recipes

Revision ID: c2cdc11b6e4c
Revises: 5b10439fdc69
Create Date: 2026-10-02 09:46:44.702602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2cdc11b6e4c'
down_revision: Union[str, Sequence[str], None] = '5b10439fdc69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('growth_stage_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['growth_stage_id'], ['growth_stages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('growth_stage_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipes')
    # ### end Alembic commands ###
